// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://firgkuabxliktgjxgskx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcmdrdWFieGxpa3Rnanhnc2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTE2NzMsImV4cCI6MjA2NTQ2NzY3M30.B7MgZYppmv_KwjphJN4VILm1PcDjrtQquJPjFmZoKDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);